#!/bin/sh

[ $# != 1 ] && {
    echo "Usage: $0 <JEP106 PDF document>"
    echo
    echo "Convert the JEDEC document containing manufacturer identification codes"
    echo "to an array initializer suitable for incusion into jep106.c. The latest"
    echo "version of the document can be found here:"
    echo "http://www.jedec.org/standards-documents/results/jep106"
    exit 1
}

echo "/* Autogenerated with $0 */" > jep106.inc
pdftotext -layout $1 - | perl -e'my $bank; while (<STDIN>) { if (/^[0-9]+[[:space:]]+(.*?)[[:space:]]+([01][[:space:]]+){8}([0-9A-F]{2})$/) {if ($3 eq "01") {$bank=$bank+1}; my $id=sprintf("0x%02x",hex($3)&0x7f); print "[$bank - 1][$id - 1] = \"$1\",\n"}};' >> jep106.inc
