
#ifndef _CONTRIB_GPERF_FREERTOS_GPERF
#define _CONTRIB_GPERF_FREERTOS_GPERF

#include <stdlib.h>
#include <string.h>

/* Generated by gperf_convert.py. Do not edit directly. */


typedef enum {
	freertos_target_name = 0,
	freertos_thread_count_width,
	freertos_pointer_width,
	freertos_list_next_offset,
	freertos_list_width,
	freertos_list_elem_next_offset,
	freertos_list_elem_content_offset,
	freertos_thread_stack_offset,
	freertos_thread_name_offset,
	freertos_option_count,
	freertos_invalid = -1,
} freertos_option_t;



struct freertos_lookup_entry { char * name; freertos_option_t option; };


struct freertos_lookup_entry * freertos_in_word_set (register const char *str, register unsigned int len);

#endif // _CONTRIB_GPERF_FREERTOS_GPERF
