name: Build and Publish to Production

on:
  push:
    tags:
      - v*

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
  call-publish:
    uses: ./.github/workflows/reusable-publish.yml
    secrets: inherit
    needs: call-build
    with:
      environment: production
      build_run_id: ${{ github.run_id }}
