name: Build Openocd for all platforms
on: [workflow_call]

jobs:

  build-mac-12:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          brew update
          brew install automake
          brew install texinfo
          export PATH=/usr/local/opt/texinfo/bin:$PATH
      - name: build-openocd
        run: |
          ./build-openocd.sh
      - name: Publish OpenOCD packaged for mac
        uses: actions/upload-artifact@v4
        with:
          name: artifact-mac-12-release
          path: ./openocd
          if-no-files-found: error

  build-linux-20-04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
          sudo apt-get install libtool
          sudo apt-get install autoconf
      - name: build-openocd
        run: |
          ./build-openocd.sh
      - name: Publish OpenOCD packaged for linux
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-20-04-release
          path: ./openocd
          if-no-files-found: error

