name: Publish
on:
  workflow_call:
    inputs:
      build_run_id:
        description: 'The run id of the build job'
        required: true
        type: string
      environment:
        description: 'The environment to publish to'
        required: true
        type: string

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v3.1.4
        with:
          run_id: ${{ inputs.build_run_id }}
          path: build/
      - name: ls build
        run: ls -la build
      - name: compress build with gz
        run: |
          ./compress-release.sh
      - name: generate manifest
        run: |
          ./generate-manifest.sh ./build ${{ secrets.BINARIES_BASE_URL }}
  upload-binaries:
    needs: download-artifacts
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        platform-arch:
          - { platform: "darwin", arch: "x64" }
          - { platform: "darwin", arch: "arm64" }
          - { platform: "linux", arch: "x64" }
          - { platform: "windows", arch: "x64" }
    steps:
      - name: Aws Assume Role
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: 'openocd-upload-session'
            aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Upload to darwin x64
        run: |
          aws s3 cp ./build/release/openocd-{platform}-${arch} s3://${{ secrets.BINARIES_BUCKET }}/openocd/${platform}/${arch} --recursive
          
