name: build-all-platforms

on:
  push:
    branches: [ "particle" ]
  pull_request:
    branches: [ "particle" ]
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
  call-publish:
    uses: ./.github/workflows/reusable-publish.yml
    secrets: inherit
    needs: call-build
    with:
      environment: staging
      build_run_id: ${{ github.run_id }}
