name: build-all-platforms

on:
  push:
    branches: [ "particle" ]
  pull_request:
    branches: [ "particle" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
        ./build-openocd.sh

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git autotools mingw-w64-ucrt-x86_64-gcc
      - name: build-openocd
        run: |
          echo 'Running in MSYS2!'
          ./build-openocd.sh
